-- 0001 — extensoes, funcoes utilitarias e tipos enumerados
-- Doc 10 §0 · correcoes do doc 16

CREATE EXTENSION IF NOT EXISTS unaccent;
CREATE EXTENSION IF NOT EXISTS pg_trgm;
CREATE EXTENSION IF NOT EXISTS citext;

-- wrapper IMMUTABLE: unaccent() e STABLE e nao pode ser indexada direto.
CREATE FUNCTION f_unaccent(text) RETURNS text
  LANGUAGE sql IMMUTABLE PARALLEL SAFE STRICT
  RETURN unaccent('unaccent', $1);

-- mantem atualizado_em coerente sem depender da aplicacao
CREATE FUNCTION set_atualizado_em() RETURNS trigger
  LANGUAGE plpgsql AS $$
BEGIN
  NEW.atualizado_em = now();
  RETURN NEW;
END $$;

CREATE TYPE sexo                 AS ENUM ('M','F');
CREATE TYPE categoria_membro     AS ENUM ('COMUNGANTE','NAO_COMUNGANTE','NAO_DEFINIDO');

CREATE TYPE situacao_membro      AS ENUM (
  'ATIVO','EM_DISCIPLINA','ROL_SEPARADO','TRANSFERENCIA_EM_CURSO','DEMITIDO');

CREATE TYPE forma_admissao       AS ENUM (
  -- comungantes (CI Art. 16)
  'PROFISSAO_FE','PROFISSAO_FE_E_BATISMO','CARTA_TRANSFERENCIA',
  'JURISDICAO_A_PEDIDO','JURISDICAO_EX_OFFICIO','RESTAURACAO','DESIGNACAO_PRESBITERIO',
  -- nao comungantes (CI Art. 17)
  'BATISMO_INFANTIL','TRANSFERENCIA_DOS_PAIS','JURISDICAO_SOBRE_OS_PAIS');

CREATE TYPE forma_demissao       AS ENUM (
  -- comungantes (CI Art. 23 + linhas do formulario CSM-IPB)
  'EXCLUSAO_DISCIPLINA','EXCLUSAO_A_PEDIDO','EXCLUSAO_POR_AUSENCIA',
  'CARTA_TRANSFERENCIA','JURISDICAO_ASSUMIDA_POR_OUTRA','FALECIMENTO',
  'ORDENACAO_AO_MINISTERIO','MOVIMENTO_PARA_ROL_SEPARADO',
  -- nao comungantes (CI Art. 24)
  'MAIORIDADE_18','PROFISSAO_FE','SOLICITACAO_DOS_PAIS');

CREATE TYPE tipo_oficio          AS ENUM ('PRESBITERO_REGENTE','DIACONO','MINISTRO');
CREATE TYPE situacao_oficio      AS ENUM ('EM_EXERCICIO','DISPONIBILIDADE','DEPOSTO','EMERITO');

CREATE TYPE motivo_fim_mandato   AS ENUM (
  'TERMINO_SEM_REELEICAO','MUDANCA_RESIDENCIA','DEPOSICAO',
  'AUSENCIA_6_MESES','EXONERACAO_ADMINISTRATIVA','EXONERACAO_A_PEDIDO','FALECIMENTO');

CREATE TYPE tipo_relacao_pastoral AS ENUM ('EFETIVO','AUXILIAR','EVANGELISTA','MISSIONARIO');

CREATE TYPE orgao_reuniao        AS ENUM (
  'CONSELHO','ASSEMBLEIA','JUNTA_DIACONAL','ORGANIZACAO_INTERNA','ADMINISTRACAO_CIVIL');

CREATE TYPE natureza_materia     AS ENUM ('ESPIRITUAL','ADMINISTRATIVA');
CREATE TYPE status_presenca      AS ENUM ('PRESENTE','AUSENTE_JUSTIFICADO','AUSENTE_NAO_JUSTIFICADO');

CREATE TYPE tipo_ato_pastoral    AS ENUM (
  'BATISMO_INFANTIL','BATISMO_ADULTO','PROFISSAO_DE_FE','SANTA_CEIA','CASAMENTO',
  'FUNERAL','VISITA_PASTORAL','ACONSELHAMENTO','UNCAO_ENFERMOS','BENCAO_APOSTOLICA');

CREATE TYPE tipo_congregacao     AS ENUM ('PONTO_DE_PREGACAO','CONGREGACAO');
